name: Docker Image CD

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: check out the codebase
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_ID}}
        aws-region: us-east-1

    - name: Login to ECR
      run: aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/q1x5a3x3    
    
    - name: Build, tag, and push the Docker image
      run: |
        docker build . -t docker-php-docker
        docker tag docker-php-docker:latest public.ecr.aws/q1x5a3x3/docker-php-docker:latest
        docker push public.ecr.aws/q1x5a3x3/docker-php-docker:latest